
# Copyright 2020 IBM. 

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
 
  NODE_ENV: development
  
  # Debug

  #############################
  ## NOTE:
  ##
  ## This debug string will apply to all pods and containers.
  ## This should be reduced on production deployments!
  ## This can be set at the container spec level for more targeted debug output
  ##
  #############################

  DEBUG: "*" # Debug string to apply to applications
  KEYCLOAK_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArIJ749pRQl4vv98txeUQ\nOd5Y12icv1rkA9nsw+pPhWMjU3YU6dypvPanT0gD9kzYBPG8FZpBwe4p2QwxV8Hv\nQINdyMiCKkmbIIZ6avNNJa4VW4PW4tiw4cSN7yZ1TauDsvcRB8iZ7Z+/JG8lKevy\nwfSsZPOprfgFJEg9jyG1DOqpETchuoVQCuoZT8F5IGOclTJd2//89veZp7K8uymJ\n8UxVoweHPOqlzLccMSu6ivjDfgFfRwKHWRZ/nP5SLHYtVsYBb8GMQ94F7c31KvcR\nY9gObZRBzkUFlor8upL/F38qZShdib+NFgCTPyoD9YC41NSST+M4DEPB3FzyKjST\nnQIDAQAB\n-----END PUBLIC KEY-----\n"
  KEYCLOAK_URL: https://auth.smartthings.com
  KEYCLOAK_REALM: development
  TOKEN_ISSUER: https://auth.smartthings.com/auth/realms/development
  TOKEN_AUDIENCE: iot_backend
  TOKEN_ALGORITHM: RS256
  TOKEN_EXPIRES_IN: "3600"

  
