
# Copyright 2020 IBM. 

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
 
  NODE_ENV: development
  
  # Debug

  #############################
  ## NOTE:
  ##
  ## This debug string will apply to all pods and containers.
  ## This should be reduced on production deployments!
  ## This can be set at the container spec level for more targeted debug output
  ##
  #############################

  ## awk -v ORS='\\n' '1' keys/keycloak-public.key | pbcopy

##############  CLOUD CONFIGURATIONS #############
  # DEBUG: "*" # Debug string to apply to applications
  # KEYCLOAK_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxTUGO/RYTIt/bbI6PdUa\n1bTfWbS990fyVKqseN14YPGFLnlAnY8dWiNxSfHxym1iDF8enBe4bWqRgoxjGUjl\nqfyhiblBSghC1AViRqMEqDQWoLcC3XXh9BrvPFNpEXyrskG2+/Bpem4nEOJhxf8W\nqo3BnZh1wCzE/SrIDcw8/nusCupjHMwj2aOte1qnRCCRr2+b4CMvEpG5wr/rL8CN\nfNQ26qTzfx58uTS1ndizKrO4G+2iomWlkGw/YSGa0jygWyQQx+ppvnF9y7L5112J\nOizsGvP0lwM3dVJMTXLrw5Deol6RS4zJD65VwEHs83QeX+zLVspq0fJ0t/QfudRN\ndQIDAQAB\n-----END PUBLIC KEY-----\n"
  # KEYCLOAK_URL: https://microservices-auth.mybluemix.net
  # KEYCLOAK_REALM: development
  # TOKEN_ISSUER: https://microservices-auth.mybluemix.net/auth/realms/development
  # TOKEN_AUDIENCE: iot_backend
  # TOKEN_ALGORITHM: RS256
  # TOKEN_EXPIRES_IN: "3600"

##############  LOCAL CONFIGURATIONS #############
  DEBUG: "*" # Debug string to apply to applications
  KEYCLOAK_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAolTAAiK+C1vu2eAfRhZO\no6QUnqLi3Vh6Dgoy8oLpVbiwZYqlpH/f4HFevKZ2Alk5k7RaGrqkPoLXsRGQHrFD\n61/ZIfzIN4A3WgaTLzgjSqnos1oMJXT0kr0BHd8i5k6w4y3KQIidhxE/7KhqZhEw\nLI6j3fVG9crMnNAj7adkAZY8oYm96IcwmuP8okfKYXLbjimxUDrGWZVHh5O9cfFJ\nqw6s5aSp7eE9K3fBOnoattm3G1yLCDf40G0oaqxaid0lQDRCF4Mem2bSfO5QCACy\np85KELIbJMG9+n7NZogu/s4Y0Y5O8Ci9J8uLKEJX/FTwGFcFsEHzwgUv7QCC/l0F\nEwIDAQAB\n-----END PUBLIC KEY-----\n
  KEYCLOAK_URL: http://keycloak-svc:8080
  KEYCLOAK_REALM: ibm
  TOKEN_ISSUER: https://microservices-auth.mybluemix.net/auth/realms/ibm
  TOKEN_AUDIENCE: account
  TOKEN_ALGORITHM: RS256
  TOKEN_EXPIRES_IN: "3600"

  
