
# Copyright 2020 IBM. 

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
 
  NODE_ENV: development
  
  # Debug

  #############################
  ## NOTE:
  ##
  ## This debug string will apply to all pods and containers.
  ## This should be reduced on production deployments!
  ## This can be set at the container spec level for more targeted debug output
  ##
  #############################

  ## awk -v ORS='\\n' '1' keys/keycloak-public.key | pbcopy

##############  CLOUD CONFIGURATIONS #############
  # DEBUG: "*" # Debug string to apply to applications
  # KEYCLOAK_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxTUGO/RYTIt/bbI6PdUa\n1bTfWbS990fyVKqseN14YPGFLnlAnY8dWiNxSfHxym1iDF8enBe4bWqRgoxjGUjl\nqfyhiblBSghC1AViRqMEqDQWoLcC3XXh9BrvPFNpEXyrskG2+/Bpem4nEOJhxf8W\nqo3BnZh1wCzE/SrIDcw8/nusCupjHMwj2aOte1qnRCCRr2+b4CMvEpG5wr/rL8CN\nfNQ26qTzfx58uTS1ndizKrO4G+2iomWlkGw/YSGa0jygWyQQx+ppvnF9y7L5112J\nOizsGvP0lwM3dVJMTXLrw5Deol6RS4zJD65VwEHs83QeX+zLVspq0fJ0t/QfudRN\ndQIDAQAB\n-----END PUBLIC KEY-----\n"
  # KEYCLOAK_URL: https://microservices-auth.mybluemix.net
  # KEYCLOAK_REALM: development
  # TOKEN_ISSUER: https://microservices-auth.mybluemix.net/auth/realms/development
  # TOKEN_AUDIENCE: iot_backend
  # TOKEN_ALGORITHM: RS256
  # TOKEN_EXPIRES_IN: "3600"

##############  LOCAL CONFIGURATIONS #############
  DEBUG: "*" # Debug string to apply to applications
  KEYCLOAK_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxH6rvuBBxH5JSXMqnN8O\n/MRDkaKaMZGUS5oQkckCrU8OMjN2N2bWSSetoHJ56CJBGv+AoSLTx1NghZ53vNqK\n8zYeQIy/ctYTGEqmebUR+GYJEdw2hUTAG0R3qqoVIQhZQemlBH40pwCMKp8/m48T\nBLUtcYo2pA5MQlg8qQPsRnM7GWOi2PN+WNEO92AKXBVlnHUTFqkZyMqQL4i+StPi\nRZuO4UFR4jRvN62YjXJ79JL403WWFiLw1QYYvwe2XKMqiMlnnT6OSW7c3jU43rnv\ncvRO/2i/pxsZaV0LzOA4U+DfUwgTUhYi6I7gaoYv/8oZfwW895q3HBBFl54bJdsh\nGwIDAQAB\n-----END PUBLIC KEY-----\n
  KEYCLOAK_URL: http://keycloak-svc:8888
  KEYCLOAK_REALM: ibm
  TOKEN_ISSUER: https://auth.smartthings.com/auth/realms/ibm
  TOKEN_AUDIENCE: account
  TOKEN_ALGORITHM: RS256
  TOKEN_EXPIRES_IN: "3600"

  
