
# Copyright 2020 IBM. 

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
 
  NODE_ENV: development
  
  # Debug

  #############################
  ## NOTE:
  ##
  ## This debug string will apply to all pods and containers.
  ## This should be reduced on production deployments!
  ## This can be set at the container spec level for more targeted debug output
  ##
  #############################

  ## awk -v ORS='\\n' '1' keys/keycloak-public.key | pbcopy

##############  CLOUD CONFIGURATIONS #############
  # DEBUG: "*" # Debug string to apply to applications
  # KEYCLOAK_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxTUGO/RYTIt/bbI6PdUa\n1bTfWbS990fyVKqseN14YPGFLnlAnY8dWiNxSfHxym1iDF8enBe4bWqRgoxjGUjl\nqfyhiblBSghC1AViRqMEqDQWoLcC3XXh9BrvPFNpEXyrskG2+/Bpem4nEOJhxf8W\nqo3BnZh1wCzE/SrIDcw8/nusCupjHMwj2aOte1qnRCCRr2+b4CMvEpG5wr/rL8CN\nfNQ26qTzfx58uTS1ndizKrO4G+2iomWlkGw/YSGa0jygWyQQx+ppvnF9y7L5112J\nOizsGvP0lwM3dVJMTXLrw5Deol6RS4zJD65VwEHs83QeX+zLVspq0fJ0t/QfudRN\ndQIDAQAB\n-----END PUBLIC KEY-----\n"
  # KEYCLOAK_URL: https://microservices-auth.mybluemix.net
  # KEYCLOAK_REALM: development
  # TOKEN_ISSUER: https://microservices-auth.mybluemix.net/auth/realms/development
  # TOKEN_AUDIENCE: iot_backend
  # TOKEN_ALGORITHM: RS256
  # TOKEN_EXPIRES_IN: "3600"

##############  LOCAL CONFIGURATIONS #############
  DEBUG: "*" # Debug string to apply to applications
  KEYCLOAK_PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAivaLi5TyZuq05IYL5+6r\nGqbO9hTd4HobLplzD8QNsM+BBKRMb58/k/z2hoz2JUr690RV5vDiKKx/Sin6f0kY\nyU0zlmVHtKf7rzEA/rMDEziYUvNuouJun+zrkUcRzSX4cOt6qhmjy+Mk2l5ix23j\n/VYW5AEQ1el6KUObwes/zKwhM7sWx650kT1V27xLnhqG+2GaIT4wXuFtrRAlUPvk\nVlojRcXOTwJh5f5hdtK0kTW7A19YlerOd6Qqqf2wKa13Wj5mCIcC8DLuQqcTESy4\nRKEfRvdm7tZ14Gnod87Xn9leWqRNh0ybFcuVEIa9l4gfEhvozElARl8iMiH5nqtn\nOwIDAQAB\n-----END PUBLIC KEY-----\n
  KEYCLOAK_URL: http://keycloak-svc:8888
  KEYCLOAK_REALM: ibm
  TOKEN_ISSUER: https://auth.smartthings.com/auth/realms/ibm
  TOKEN_AUDIENCE: account
  TOKEN_ALGORITHM: RS256
  TOKEN_EXPIRES_IN: "3600"

  
