
# Copyright 2020 IBM. This code is licensed only for use with IBM Watson Services

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-iot-api
  labels:
    set: ms-iot-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-iot-api
        set: ms-iot-api
    spec:
      containers:
        - name: ms-iot-api
          image: sinny777/microservice-iot:latest
          envFrom:
          - configMapRef:
              name: env-config
          env:
          - name: NODE_ENV
            value: "development"
          - name: DB_CONNECTOR
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: DB_CONNECTOR
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: DB_URL
          - name: USER_TEMP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: USER_TEMP_PASSWORD
          - name: ACCOUNTS_KEYS_PATH
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: ACCOUNTS_KEYS_PATH
          - name: TOKEN_ISSUER
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: TOKEN_ISSUER
          - name: TOKEN_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: TOKEN_AUDIENCE
          - name: TOKEN_ALGORITHM
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: TOKEN_ALGORITHM
          - name: TOKEN_EXPIRES_IN
            valueFrom:
              secretKeyRef:
                name: accounts-secrets
                key: TOKEN_EXPIRES_IN
          ports:
          - containerPort: 3001     
      restartPolicy: Always

