
# Copyright 2020 IBM. 

apiVersion: v1
kind: Service
metadata:
  name: account-svc
  labels:
    app: smartthings-account
    tier: accounts
spec:
  # type: LoadBalancer
  ports:
  - port:  3000
    targetPort: 3000
  selector:
   app: smartthings-account
status:
  loadBalancer: {}
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartthings-account
  labels:
    app: smartthings-account
    tier: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartthings-account
  template:
    metadata:
      labels:
        app: smartthings-account        
    spec:
      containers:
      - name: smartthings-account
        image: sinny777/smartthings-account:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: DB_CONNECTOR
            value: "mongodb"
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: DB_URL          
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: account-secrets
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: account-secrets
                key: CLIENT_SECRET
          - name: PORT
            value: "3000"        
        ports:
        - name: http
          containerPort: 3000   
      restartPolicy: Always

