
# Copyright 2020 IBM. 

apiVersion: v1
kind: Service
metadata:
  name: smartthings-iot-svc
  labels:
    app: smartthings-iot
    tier: iot
spec:
  ports:
  - port:  80
    targetPort: 3000
  selector:
   app: smartthings-iot
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartthings-iot
  labels:
    app: smartthings-iot
    tier: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartthings-iot
  template:
    metadata:
      labels:
        app: smartthings-iot        
    spec:
      containers:
      - name: smartthings-iot
        image: smartthings-iot:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: DB_CONNECTOR
            value: "mongodb"
          - name: DB_URL
            value: ""
          - name: DB_HOST
            value: "mongodb-svc"
          - name: DB_PORT
            value: "27017"
          - name: DB_NAME
            value: "smartthings"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: DB_PASSWORD
          - name: PORT
            value: "3000"  
        ports:
        - name: http
          containerPort: 3000   
      restartPolicy: Always

