
# Copyright 2020 IBM. 

apiVersion: v1
kind: Service
metadata:
  name: smartthings-iot-svc
  labels:
    app: smartthings-iot
    tier: iot
spec:
  ports:
  - port:  80
    targetPort: 3000
  selector:
   app: smartthings-iot
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartthings-iot
  labels:
    app: smartthings-iot
    tier: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartthings-iot
  template:
    metadata:
      labels:
        app: smartthings-iot        
    spec:
      containers:
      - name: smartthings-iot
        image: smartthings-iot:localtag
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: PORT
          value: "3000"  
        ports:
        - name: http
          containerPort: 3000   
      restartPolicy: Always

