
# Copyright 2020 IBM. 

apiVersion: v1
kind: Service
metadata:
  name: iot-svc
  labels:
    app: smartthings-iot
    tier: iot
spec:
  # type: LoadBalancer
  ports:
  - port:  3000
    targetPort: 3000
  selector:
   app: smartthings-iot
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartthings-iot
  labels:
    app: smartthings-iot
    tier: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartthings-iot
  template:
    metadata:
      labels:
        app: smartthings-iot        
    spec:
      containers:
      - name: smartthings-iot
        image: sinny777/smartthings-iot:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: DB_CONNECTOR
            value: "mongodb"
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: DB_URL 
          - name: COGNOS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: cognos-secrets
                key: COGNOS_ENDPOINT
          - name: COGNOS_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: cognos-secrets
                key: COGNOS_CLIENT_ID
          - name: COGNOS_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: cognos-secrets
                key: COGNOS_CLIENT_SECRET
          - name: PORT
            value: "3000"  
        ports:
        - name: http
          containerPort: 3000   
      restartPolicy: Always

