
# Copyright 2020 IBM. This code is licensed only for use with IBM Watson Services

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
 
  NODE_ENV: development
  
  # Debug

  #############################
  ## NOTE:
  ##
  ## This debug string will apply to all pods and containers.
  ## This should be reduced on production deployments!
  ## This can be set at the container spec level for more targeted debug output
  ##
  #############################

  DEBUG: "*" # Debug string to apply to applications
  # POSTGRES_HOST: postgres-svc
  POSTGRES_HOST: "hanno.db.elephantsql.com"
  POSTGRES_PORT: "5432"
  
