# This is a basic workflow to help you get started with Actions

name: Docker Build and Push CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build Accounts Service
      run: |
        docker build ./services/accounts -t sinny777/smartthings-account:latest
    - name: Build IoT Service
      run: |
        docker build ./services/iot -t sinny777/smartthings-iot:latest
    - name: Build CarbonUI Service
      run: |
        docker build ./client/carbon_ui -t sinny777/smartthings-carbon_ui:latest
    # - name: Build CustomUI Service
    #   run: |
    #     docker build ./client/custom_ui -t sinny777/smartthings-custom_ui:latest
    - name: Docker Push
      run: |
        echo Pushing All services to Dockerhub,
        docker push sinny777/smartthings-account:latest
        docker push sinny777/smartthings-iot:latest
        docker push sinny777/smartthings-carbon_ui:latest
    #     docker push sinny777/smartthings-custom_ui:latest
